---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app "${APP}"
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      tubearchivist:
        containers:
          app:
            image:
              repository: bbilly1/tubearchivist
              tag: v0.5.8@sha256:83ccd1e372a654654e8cb3c0278256b6889653a4cf239c052bb532401c79daeb
            env:
              TZ: "${TIMEZONE}"
              HOST_UID: 568
              HOST_GID: 1234
              ES_URL: http://tubearchivist-elasticsearch:9200
              REDIS_CON: redis://dragonfly-tubearchivist:6379
              TA_HOST: https://tubearchivist.${SECRET_DOMAIN}
              TA_USERNAME: admin
              DISABLE_STATIC_AUTH: "true"
            envFrom:
              - secretRef:
                  name: *app
            resources:
              requests:
                cpu: 1000m
                memory: 512Mi
            securityContext:
              fsGroup: 1234
              capabilities:
                add:
                  - CHOWN
    service:
      app:
        controller: tubearchivist
        ports:
          http:
            port: &port 8000

    route:
      app:
        hostnames: ["tubearchivist.${SECRET_DOMAIN}"]
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: Tubearchivist
          gethomepage.dev/group: Downloads
          gethomepage.dev/icon: tube-archivist.png
          gethomepage.dev/app: tubearchivist-web
          gethomepage.dev/widget.type: tubearchivist
          gethomepage.dev/widget.url: http://tubearchivist.downloads.svc.cluster.local
          gethomepage.dev/widget.key: '{{`{{HOMEPAGE_VAR_TUBEARCHIVIST_TOKEN}}`}}'
        rules:
          - backendRefs:
              - name: "tubearchivist-web"
                port: *port
    persistence:
      cache:
        enabled: true
        existingClaim: *app
      downloads:
        type: emptyDir
        sizeLimit: 10Gi
      youtube:
        type: nfs
        server: ${NAS_IP}
        path: ${NAS_PATH}/data/youtube
