apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
configMapGenerator:
  - name: node-red-configmap
    files:
      - ./resources/settings.js
generatorOptions:
  disableNameSuffixHash: true
