---
# yaml-language-server: $schema=https://schemas.tholinka.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &app "${APP}"
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: *app
    creationPolicy: Owner
    template:
      data:
        # DB Init
        INIT_POSTGRES_DBNAME: *app
        INIT_POSTGRES_HOST: postgres-cluster-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: &dbuser '{{ .PENPOT_POSTGRES_USER }}'
        INIT_POSTGRES_PASS: &dbpass '{{ .PENPOT_POSTGRES_PASS }}'

        # Penpot Database
        PENPOT_DATABASE_USERNAME: *dbuser
        PENPOT_DATABASE_PASSWORD: *dbpass

        # Penpot secrets
        PENPOT_SECRET_KEY: '{{ .PENPOT_SECRET_KEY }}'
        PENPOT_OIDC_BASE_URI: '{{ .PENPOT_OIDC_BASE_URI }}'
        PENPOT_OIDC_CLIENT_ID: '{{ .PENPOT_OIDC_CLIENT_ID }}'
        PENPOT_OIDC_CLIENT_SECRET: '{{ .PENPOT_OIDC_CLIENT_SECRET }}'

        # Penpot config
        PENPOT_FLAGS: enable-smtp enable-prepl-server enable-login-with-oidc
        PENPOT_HTTP_SERVER_MAX_BODY_SIZE: '31457280'
        PENPOT_HTTP_SERVER_MAX_MULTIPART_BODY_SIZE: '367001600'

        # Penpot SMTP
        PENPOT_SMTP_DEFAULT_FROM: 'Penpot <{{ .EMAIL_FROM }}>'
        PENPOT_SMTP_DEFAULT_REPLY_TO: 'Penpot <{{ .EMAIL_FROM }}>'
        PENPOT_SMTP_HOST: '{{ .EMAIL_SERVER }}'
        PENPOT_SMTP_PORT: '587'
        PENPOT_SMTP_USERNAME: '{{ .EMAIL_USER }}'
        PENPOT_SMTP_PASSWORD: '{{ .PENPOT_SMTP_PASSWORD }}'
        PENPOT_SMTP_TLS: 'true'
        PENPOT_SMTP_SSL: 'false'

  dataFrom:
    - extract:
        key: *app
    - extract:
        key: email
---
# yaml-language-server: $schema=https://schemas.tholinka.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &app "${APP}-initdb"
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: *app
    creationPolicy: Owner
    template:
      data:
        INIT_POSTGRES_SUPER_USER: '{{ .POSTGRES_SUPER_USER }}'
        INIT_POSTGRES_SUPER_PASS: '{{ .POSTGRES_SUPER_PASS }}'
  dataFrom:
    - extract:
        key: cloudnative_pg
