---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app "${APP}"
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  driftDetection:
    mode: enabled
    ignore:
      - paths: [/spec/replicas]
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      *app :
        annotations:
          reloader.stakater.com/auto: 'true'
        initContainers:
          init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: 17
            envFrom:
              - secretRef:
                  name: *app
              - secretRef:
                  name: penpot-initdb
        containers:
          frontend:
            dependsOn:
              - backend
              - exporter
            image:
              repository: penpotapp/frontend
              tag: 2.12.1@sha256:e6f20a1ce5224e3cec4bbdb63892319bcf7e751c95b4baff8b1343e3fac668d6
            env:
              PENPOT_PUBLIC_URI: https://penpot.${SECRET_DOMAIN}
              PENPOT_BACKEND_URI: http://penpot-backend.self-hosted.svc.cluster.local:6060
              PENPOT_EXPORTER_URI: http://penpot-exporter.self-hosted.svc.cluster.local:6061
            envFrom:
              - secretRef:
                  name: *app
          backend:
            image:
              repository: penpotapp/backend
              tag: 2.12.1@sha256:8400aeccabc564c2c23ef5ebbc087d6382044f4ffa45e2d7db260a73c6eac398
            env:
              PENPOT_PUBLIC_URI: https://penpot.${SECRET_DOMAIN}
              PENPOT_DATABASE_URI: postgresql://postgres-cluster-rw.database.svc.cluster.local/{{ .PENPOT_POSTGRES_DBNAME }}
              PENPOT_REDIS_URI: redis://dragonfly-cluster.database.svc.cluster.local:6379
              PENPOT_ASSETS_STORAGE_BACKEND: assets-fs
              PENPOT_STORAGE_ASSETS_FS_DIRECTORY: /opt/data/assets
              PENPOT_TELEMETRY_ENABLED: false
            envFrom:
              - secretRef:
                  name: *app
          exporter:
            image:
              repository: penpotapp/exporter
              tag: 2.12.1@sha256:a245ec857c2c5cc7e8702309134312d459af086a2bd2e07983d5cf1d3f30e841
            env:
              PENPOT_PUBLIC_URI: https://penpot.${SECRET_DOMAIN}
              PENPOT_REDIS_URI: redis://dragonfly-cluster.database.svc.cluster.local:6379
            envFrom:
              - secretRef:
                  name: *app
    service:
      frontend:
        primary: true
        forceRename: *app
        ports:
          http:
            primary: true
            port: &port 8080
      backend:
        ports:
          http:
            port: 6060
      exporter:
        ports:
          http:
            port: 6061
      prepl:
        ports:
          http:
            port: 6062

    route:
      app:
        hostnames: ["penpot.${SECRET_DOMAIN}"]
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: Penpot
          gethomepage.dev/group: Design
          gethomepage.dev/icon: penpot.png
          gethomepage.dev/app: penpot
        rules:
          - backendRefs:
              - name: *app
                port: *port
    persistence:
      assets:
        enabled: true
        existingClaim: *app
        advancedMounts:
          *app :
            frontend:
              - path: /opt/data/assets
            backend:
              - path: /opt/data/assets

