---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &app "${APP}"
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: *app
    creationPolicy: Owner
    template:
      data:
        ACTUAL_OPENID_DISCOVERY_URL: '{{ .ACTUAL_OPENID_DISCOVERY_URL }}'
        ACTUAL_OPENID_CLIENT_ID: '{{ .ACTUAL_OPENID_CLIENT_ID }}'
        ACTUAL_OPENID_CLIENT_SECRET: '{{ .ACTUAL_OPENID_CLIENT_SECRET }}'
        ACTUAL_OPENID_SERVER_HOSTNAME: 'https://${APP}.${SECRET_DOMAIN}'
        ACTUAL_OPENID_ENFORCE: 'false'
        ACTUAL_TOKEN_EXPIRATION: 'openid-provider'
  dataFrom:
    - extract:
        key: *app
