---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &app "${APP}"
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: *app
    creationPolicy: Owner
    template:
      data:
        # DB Init
        INIT_POSTGRES_DBNAME: *app
        INIT_POSTGRES_HOST: &dbhost postgres-cluster-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: *app
        INIT_POSTGRES_PASS: &dbpass '{{ .DB_PASSWORD }}'

        # Tandoor
        SECRET_KEY: '{{ .SECRET_KEY }}'
        DB_ENGINE: django.db.backends.postgresql
        POSTGRES_HOST: *dbhost
        POSTGRES_DB: *app
        POSTGRES_PORT: "5432"
        POSTGRES_USER: *app
        POSTGRES_PASSWORD: *dbpass
  dataFrom:
    - extract:
        key: *app
---
# yaml-language-server: $schema=https://schemas.tholinka.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret outline-initdb
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: *secret
    creationPolicy: Owner
    template:
      data:
        INIT_POSTGRES_SUPER_USER: '{{ .POSTGRES_SUPER_USER }}'
        INIT_POSTGRES_SUPER_PASS: '{{ .POSTGRES_SUPER_PASS }}'
  dataFrom:
    - extract:
        key: cloudnative_pg
